SYSTEM         = Linux
PREFIX         = /usr/local
LOCALEDIR      = 
BEOS_NETSERVER = no
PTHREAD        = yes
OPENSSL        = yes
GTK            = no
CC             = cc
CFLAGS         = 
CXX            = c++
CXXFLAGS       = 
LDFLAGS        = 
CFLAGS_GTK     = 
LDFLAGS_GTK    = 
